### ISSUE TITLE
Error installing vscode.d.ts: Error: Request returned status code: 500

### ISSUE THREAD

**Issue by roonyh** [Microsoft/vscode-extension-vscode#145] opened 2019-03-01 13:15 UTC
I get above error when doing `npm i`

When inspecting I noticed request to the following url fails.
https://vscode-update.azurewebsites.net/api/releases/stable

**Comment by bpasero** [comment] 2019-03-01 13:46
Duplicate of https://github.com/Microsoft/vscode/issues/69656

**Closed by bpasero** 2019-03-01 13:46 UTC

**Comment by ShMcK** [comment] 2019-06-02 04:13
Although the issue has been closed, the error is occuring for me.

```
Detected VS Code engine version: ^1.34.0
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error
```

Note that microsoft/vscode#69565 is closed for comment.

**Comment by ShMcK** [comment] 2019-06-02 15:28
Seems to be working this morning. All good.
