### ISSUE TITLE
Tests: ensure version of Code in .vscode-test matches the one expected

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-extension-vscode#96] opened 2018-03-04 16:45 UTC
Currently if you have a `.vscode-test` folder locally, the test script will use the version inside it even if it's stale/doesn't match the `CODE_VERSION`.

This is likely a fringe case - people will run tests locally using the launch config and on Travis/AppVeyor they'll likely start with a clean filesystem.

However, if you might want to speed things up by reusing folders (eg. if you use Travis/AppVeyor caches to avoid re-downloading dependencies on all builds) then this fix would be required to avoid getting stuck running tests on an old version.

**Comment by gkalpak** [comment] 2018-09-07 11:05
I just ran into this 😒 Quite unexpected behavior 😕

I assume it is not a high priority, since it has been open since March :grin:
Maybe at least [the docs][1] could be updated to mention that you need to clear `.vscode-test/` if you want `CODE_VERSION` to take effect.

##
That said, from a quick look at [bin/test][2] it looks like an easy fix (famous last words :grin:).
I'd be happy to work on it, if this is something you are interested in getting fixed, @bpasero.

[1]: https://github.com/Microsoft/vscode-docs/blob/dc1792fded1fba89f6914a79ffd974d35c3e2869/docs/extensions/testing-extensions.md
[2]: https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/test

**Comment by gkalpak** [comment] 2018-09-09 07:54
BTW, the same is true for `CODE_DOWNLOAD_URL`. It is only used if there is not version already present in `.vscode-test/`.

**Comment by gkalpak** [comment] 2018-09-10 16:26
If anyone is interested, [this is the script][1] I currently use to handle testing against a specific version. It seems to work fine so far (on Windows, Linux, and macOS ✌️), but still use at your own rist :grin:

<sub>(For more context on how I am using it, this is the whole commit: gkalpak/aio-docs-utils@c1ee381a4)</sub>

[1]: https://github.com/gkalpak/aio-docs-utils/blob/1dd387d1e902efb14b37fdcdcd643924d1ad3b77/src/test/helpers/e2e-runner.ts

**Comment by octref** [comment] 2019-03-20 05:11
This is fixed by https://github.com/Microsoft/vscode-extension-vscode/pull/148.

Now VS Code is downloaded to `.vscode-test/vscode-1.32` when you run `yarn test`. When 1.33 is released, new versions will be downloaded to `.vscode-test/vscode-1.33` and used for running tests.

For more granular control, use `vscode-test` directly instead of relying on `vscode`: https://github.com/microsoft/vscode-test.

**Closed by octref** 2019-03-20 05:11 UTC
Labels: feature request

**Comment by gkalpak** [comment] 2019-03-20 08:48
Thx for working on this, @octref 👍
I spotted some issues and submitted fixes in #155 and Microsoft/vscode-test#1.

**Comment by DanTup** [comment] 2019-03-20 08:59
@octref I think all the code referencing `testRunFolderAbsolute` may be dead now and should be removed? If I'm reading the code correctly, this `console.log` looks suspicious:

```
function downloadExecutableAndRunTests() {
    console.log('Downloading VS Code into "' + testRunFolderAbsolute); // <-- 

    downloadAndUnzipVSCode().then(executablePath => {
        executable = executablePath
        runTests()
    })
```

AFAICT `downloadAndUnzipVSCode` does its own calculation of the download folder (including the version number) and `testRunFolderAbsolute` is the old path (ending in stable, or w/e)?

**Comment by DanTup** [comment] 2019-03-20 09:02
Actually, maybe it's deliberate, since the "old" `runTests` method is still used:

```
fs.exists(executable, function (exists) {
    if (exists) {
        runTests();
    } else {
        downloadExecutableAndRunTests();
    }
});
```

It's not clear why, though I guess probably it's intended. I'll try switch over to using the package directly, as I already have a script for running my tests (but was shelling out to the old script). Hopefully this will simplify things :-)
